# Generated by Django 3.2.17 on 2023-02-10 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0002_add_resolved_by_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="resolved_at",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="resolved_by",
        ),
        migrations.CreateModel(
            name="TicketResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Resolution Time"
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution",
                        related_query_name="resolution",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
