# Generated by Django 3.2.18 on 2023-03-26 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0005_move_to_ticket_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketEventAssigneeChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticketeventassigneechange",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketevent",
            name="assignee_change",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.ticketeventassigneechange",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="ticketevent",
            name="at_least_event_or_comment_set",
        ),
        migrations.AddConstraint(
            model_name="ticketevent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("new_status__exact", ""), _negated=True),
                        models.Q(("comment__exact", ""), _negated=True),
                        ("assignee_change__isnull", False),
                        _connector="OR",
                    ),
                ),
                name="valid_event",
            ),
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="assignee",
        ),
    ]
