# Generated by Django 4.2.11 on 2025-03-22 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0004_add_team_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["tla"]},
        ),
        migrations.CreateModel(
            name="TeamAttendanceEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("ARRIVED", "Arrived"),
                            ("LEFT", "Left"),
                            ("DELAYED", "Delayed"),
                            ("DROPPED_OUT", "Dropped Out"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=11,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_attendance_events",
                        related_query_name="team_attendance_events",
                        to="teams.team",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
