# Generated by Django 5.2.12 on 2026-03-18 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_options_teamattendanceevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBatteryLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_1_asset_code', models.CharField(max_length=7, verbose_name='Battery 1 Asset Code')),
                ('battery_2_asset_code', models.CharField(max_length=7, verbose_name='Battery 2 Asset Code')),
                ('charger_asset_code', models.CharField(max_length=7, verbose_name='Charger Asset Code')),
                ('charger_psu_asset_code', models.CharField(max_length=7, verbose_name='Charger PSU Asset Code')),
                ('battery_bag_asset_code', models.CharField(max_length=7, verbose_name='Battery Bag Asset Code')),
                ('notes', models.CharField(max_length=100, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
