# Generated by Django 4.2.20 on 2026-03-16 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0005_alter_team_options_teamattendanceevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("SAFETY_CHECK_PASS", "Safety Check (Pass)"),
                            ("SAFETY_CHECK_FAIL", "Safety Check (Fail)"),
                            ("REGS_CHECK_PASS", "Regulations Check (Pass)"),
                            ("REGS_CHECK_FAIL", "Regulations Check (Fail)"),
                        ],
                        max_length=17,
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
