# Generated by Django 3.2.17 on 2023-02-08 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_create_ticket_models"),
        ("accounts", "0001_create_user_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_ticket_queue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.ticketqueue",
                verbose_name="Default Ticket Queue",
            ),
        ),
    ]
