# Generated by Django 3.2.18 on 2023-03-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_add_missing_unique_constraint"),
        ("accounts", "0003_auto_20230318_1405"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="default_ticket_queue",
            field=models.ForeignKey(
                blank=True,
                help_text="If no queue is selected, the Teams list will be used as the default",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.ticketqueue",
                verbose_name="Default Ticket Queue",
            ),
        ),
    ]
