name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.9, "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      # Workaround for https://github.com/jazzband/pip-tools/issues/2131
      - name: Downgrade pip
        run: pip install --upgrade pip==24.2

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Validate dependencies
        uses: PeterJCLaw/validate-generated-files@v1
        if: matrix.python == '3.10'
        with:
          command: ./script/compile-requirements.sh
          files: requirements*.txt

      - name: Use the dev configuration
        run: cp helpdesk/helpdesk/configuration.dev.py helpdesk/helpdesk/configuration.py

      - name: Static type checking
        run: make type

      - name: Formatting
        run: make format-check

      - name: Lint
        run: make lint

      - name: Unit tests
        run: make test

      - name: Django Static Checks
        run: make check
